<?php

namespace ClassroomBundle\Repository;
use ClassroomBundle\Entity\Classroom;

/**
 * ClassroomRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClassroomRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param Classroom $classroom
     */
    public function save(Classroom $classroom)
    {
        $this->_em->persist($classroom);
        $this->_em->flush();
    }

    /**
     * @param Classroom $classroom
     */
    public function delete(Classroom $classroom)
    {
        $this->_em->remove($classroom);
        $this->_em->flush();
    }
}
