# https://github.com/nelmio/NelmioCorsBundle/blob/master/README.md
#nelmio_cors:
#    defaults:
#        allow_credentials: false
#        allow_origin: []
#        allow_headers: []
#        allow_methods: []
#        expose_headers: []
#        max_age: 0
#        hosts: []
#        origin_regex: false
#        forced_allow_origin_value: false
#    paths:
#        '^/api/':
#            allow_credentials: true
#            allow_origin: ['*']
#            allow_headers: ['*']
#            allow_methods: ['POST', 'GET', 'PUT', 'DELETE', 'OPTIONS']
#            max_age: 3600 # one hour

# FOSRest Configuration
fos_rest:
    body_listener: true
    format_listener:
        rules:
            - { path: '^/api/', priorities: ['json'], fallback_format: json, prefer_extension: true }
            - { path: '^/', priorities: [ 'html', '*/*'], fallback_format: ~, prefer_extension: true }
    param_fetcher_listener: true
    routing_loader:
        include_format: false
    view:
        view_response_listener: 'force'
        formats:
            json: true
    exception:
        codes:
            'InvalidArgumentException': 400
            'DomainException': 400
            'LogicException': 400
            'Symfony\Component\Routing\Exception\ResourceNotFoundException': 404
            'Symfony\Component\Security\Core\Exception\AccessDeniedException': 403
        messages:
            'InvalidArgumentException': true
            'DomainException': true
            'LogicException': true
            'Symfony\Component\Routing\Exception\ResourceNotFoundException': true
            'Symfony\Component\Security\Core\Exception\AccessDeniedException': true
